version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: gestion_etudiants
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Paris
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 15s
      timeout: 3s
      retries: 20

  back:
    build:
      context: ./gestion-scolaire-back
      dockerfile: Dockerfile
    image: gestion-scolaire-back:latest
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./gestion-scolaire-back/.env
    environment:
      NODE_ENV: production
      PORT: "3000"
      DB_HOST: mysql
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: gestion_etudiants
    expose:
      - "3000"
    volumes:
      - back_uploads:/app/uploads

  front:
    build:
      context: ./gestion-scolaire-front/gestion-scolaire
      dockerfile: Dockerfile
    image: gestion-etudiants:latest
    depends_on:
      - back
    expose:
      - "80"

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"    # HTTP public
      - "443:443"  # HTTPS public
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - front
      - back

volumes:
  mysql_data:
  back_uploads:
  npm_data:
  npm_letsencrypt:

